<?php


namespace App\Admin\Controllers;


use App\Http\Controllers\Controller;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpKernel\Exception\ServiceUnavailableHttpException;

abstract class _InspectorBasedController extends Controller
{

    use InspectorControllerTrait;

    const PAGE_SIZE = 10;

    /**
     * @return void
     */
    abstract protected function initialize();


    public function callAction($method, $parameters)
    {
        $this->initialize();
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
}