<?php


namespace App\Admin\Controllers;


use App\Http\Controllers\Controller;

abstract class _InspectorBasedController extends Controller
{

    use InspectorControllerTrait;

    const PAGE_SIZE = 10;

    /**
     * @return void
     */
    abstract protected function initialize();


    public function callAction($method, $parameters)
    {
        $this->initialize();
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
}